GoogleCloudPlatform/k8s-service-catalog

installer/Gopkg.lock, installer/Gopkg.toml, installer/cmd/main.go, installer/cmd/templates.go, installer/vendor/github.com/golang/glog/LICENSE, installer/vendor/github.com/golang/glog/README, installer/vendor/github.com/golang/glog/glog.go, installer/vendor/github.com/golang/glog/glog_file.go, installer/vendor/github.com/golang/glog/glog_test.go
This is a straight forward change, so merging it myself.
=> added glog library and minor refactoring

installer/hack/gcp/gcp-bigquery-binding.yaml, installer/hack/gcp/gcp-bigquery-instance.yaml
=> BigQuery instance and binding templates

installer/examples/gcp-pubsub-app/service-binding.yaml, installer/examples/gcp-pubsub-app/service-instance.yaml, installer/hack/gcp/gcp-pubsub-binding.yaml, installer/hack/gcp/gcp-pubsub-instance.yaml
=> update pubsub yaml files for recent service definition update

installer/hack/gcp/gcp-storage-binding.yaml, installer/hack/gcp/gcp-storage-instance.yaml
=> add GCS instance binding template files

installer/hack/gcp/gcp-sql-binding.yaml, installer/hack/gcp/gcp-sql-instance.yaml
=> cloudSQL instance and binding templates

installer/service-catalog-pubsub-tutorial.md
Also wrap -o formatters with quotes (my shell tried to interpolate)
=> Update tutorial with current type names

installer/README.md
Adds links to cfssl and the Google Cloud SDK
Signed-off-by: Lorenzo Manacorda <lorenzo@kinvolk.io>
=> README: Add links to dependencies

broker-cli/pkg/auth/auth.go, broker-cli/pkg/client/adapter/adapter.go, broker-cli/pkg/client/adapter/httpadapter.go, broker-cli/pkg/client/adapter/httpadapter_test.go, broker-cli/pkg/client/osb/types.go
=> Copy installer/pkg/broker-cli to broker-cli/pkg

installer/pkg/cmd/service_catalog.go
=> added check for etcd-backup-storageclass

installer/Gopkg.lock, installer/pkg/cmd/service_catalog.go, installer/vendor/github.com/Masterminds/semver/.travis.yml, installer/vendor/github.com/Masterminds/semver/CHANGELOG.md, installer/vendor/github.com/Masterminds/semver/LICENSE.txt, installer/vendor/github.com/Masterminds/semver/Makefile, installer/vendor/github.com/Masterminds/semver/README.md, installer/vendor/github.com/Masterminds/semver/appveyor.yml, installer/vendor/github.com/Masterminds/semver/benchmark_test.go, installer/vendor/github.com/Masterminds/semver/collection.go, installer/vendor/github.com/Masterminds/semver/collection_test.go, installer/vendor/github.com/Masterminds/semver/constraints.go, installer/vendor/github.com/Masterminds/semver/constraints_test.go, installer/vendor/github.com/Masterminds/semver/doc.go, installer/vendor/github.com/Masterminds/semver/version.go, installer/vendor/github.com/Masterminds/semver/version_test.go
=> added server version (1.7+) check

installer/cmd/sc/main.go, installer/pkg/cmd/gcp_broker.go, installer/pkg/cmd/service_catalog.go, installer/pkg/cmd/templates.go, installer/pkg/cmd/update.go, installer/pkg/cmd/version.go
=> sc exits with non-zero code on errors.

installer/pkg/cmd/templates.go, installer/pkg/gcp/broker.go
=> bubble up gcloud CLI errors

installer/README.md
Usage breaks if the requirements are not met.
=> Move requirements to above usage.

installer/README.md
updated the "go get" instructions. `-u` flag is needed.
=> Updated the README

installer/pkg/cmd/gcp_broker.go, installer/pkg/cmd/service_catalog.go
=> Wait for the completion of deleting namespace in sc uninstall command

installer/pkg/cmd/gcp_broker.go, installer/pkg/cmd/templates.go, installer/pkg/gcp/broker.go
=> Create one service account per cluster instead of reusing the same SA

installer/pkg/cmd/gcp_broker.go, installer/pkg/gcp/broker.go
=> Remove the newly generated key if sc add-gcp-broker command fails

installer/pkg/cmd/templates.go, installer/templates/sc/tls-cert-secret.yaml.tmpl
=> Set correct secret type for tls-cert

catalog-oauth/auth/google_oauth.go, catalog-oauth/auth/google_oauth_test.go, catalog-oauth/main.go
- make sure errors logged are actual errors
- log successful auth token creation
=> Improve logging in oauth component

installer/pkg/broker-cli/client/adapter/httpadapter.go, installer/pkg/cmd/gcp_broker.go
The API does not accept list of catalogs.
=> Do not pass list of catalogs to CreateBroker

installer/pkg/cmd/service_catalog.go
=> restart controller-manager and apiserver pods during `sc install`

installer/cloudbuild.yaml
This builds sc, cfssl, and cfssljson binaries.  This is a start towards
automated binary release builds.
=> Add a proof-of-concept Google Cloud Container Builder config.

broker-cli/cmd/flags/brokerurl.go
This is better than the check before.
=> Making partslen accurate

.travis.yml, broker-cli/Makefile, scripts/build.sh
Plan is to add a test check too.
=> Add Travis support for broker CLI, we only checks that build works atm

installer/pkg/cmd/gcp_broker.go
Removing title as existing title maybe different. No way to know as there is no Get Broker.
=> Improving how we handle the case of the existing EAP broker

installer/pkg/cmd/templates.go, installer/templates/sc/api-registration.yaml.tmpl
=> sc install on GKE 1.11.2-gke.18 fails with unknown field priority #216
